### ISSUE TITLE
What is the 0.2.0 branch for

### ISSUE THREAD

**Issue by CrowdHailer** [tanguilp/wax#15]
Hi, I've been looking to see if I can contribute, or use Wax for my purposes.
Just spotted that there is an open branch with a lot of stuff on and don't want to duplicate work.

Could you open a PR for that branch?

**Comment by tanguilp** [comment]
On the `0.2.0` branch I'm actually finishing this library, mainly by:
- implementing the remaining signature algorithms (RSA-PSS, secp256k1, ed...). You can refer to the updated README of this branch
- testing against the official test suite from the FIDO foundation

I plan to release v0.2.0 within 6-8 weeks when it's done. The library will then be almost completed.

I'd be glad to receive bug reports or any question regarding the code (FIDO2 is a complex protocol).

I've opened a draft PR. However I'm not sure to have time to review massive code changes and I'm reluctant to accept PRs for such a sensitive library (because it requires diving into the WebAuthn / FIDO2/ TPM... documentation to remember "why", which is very time consuming, see for example: https://github.com/tanguilp/wax/pull/4).

**Comment by tanguilp** [comment]
FYI I'm using the following libs for testing against the official test suite (instructions inside):
- https://github.com/tanguilp/wax_fido_test_suite_server
- https://github.com/tanguilp/wax_api_rest
