### ISSUE TITLE
FunctionClauseError no function clause matching in Wax.Metadata.Statement.user_verification_method/1

### ISSUE THREAD

**Issue by dfalling** [tanguilp/wax#19]
Wax is crashing on startup for me.  I get this message numerous times, until my server actually runs out of memory and erlang crashes.

```
[error] Task Wax.Metadata started from #PID<0.3294.0> terminating
** (FunctionClauseError) no function clause matching in Wax.Metadata.Statement.user_verification_method/1
    (wax_ 0.3.0) lib/wax/metadata/statement.ex:434: Wax.Metadata.Statement.user_verification_method(2048)
    (wax_ 0.3.0) lib/wax/metadata/statement.ex:349: anonymous fn/1 in Wax.Metadata.Statement.from_json!/1
    (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (wax_ 0.3.0) lib/wax/metadata/statement.ex:342: Wax.Metadata.Statement.from_json!/1
    (elixir 1.10.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.9.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<7.27430003/0 in Wax.Metadata.process_metadata_toc/2>
    Args: []
```

The only changes I've made to my codebase in the last few days are other unrelated packages- ex_aws, pow, phoenix_live_dashboard, so I don't _think_ any of them could be causing this.  Any idea what's going on?

**Comment by tanguilp** [comment]
Yes, they are publishing an invalid metadata statement. I've written to them this afternoon, no response so far.

The Yubikey metadata statement has a user verification method with value 0x800, which is not accepted so far: https://github.com/tanguilp/wax/blob/master/lib/wax/metadata/statement.ex#L444

Feel free to add an entry for this in a forked version if needed, otherwise I'm waiting beginning of the coming week to fix it if needed.

**Comment by dfalling** [comment]
Got it, thanks for the quick response!  Any thoughts on how to more gracefully handle failures like these?  I'm happy to contribute but am not sure where to start.

**Comment by tanguilp** [comment]
Got the response from FIDO2 alliance people, they say they'll fix it tomorrow.

Could be more robust but I'm reluctant to do it because the MDSv2 metadata should be compliant with their _own_ specs... Will ask them if it's worth writing defensive code.

**Comment by tanguilp** [comment]
This has been fixed in 0.3.1. Please feel free to report that it works well on your side too.

The problem was that they silently updated the specification adding some new possible values, and even seemed not to be aware of that. So the metadata was correct in regards to https://fidoalliance.org/specs/common-specs/fido-registry-v2.1-ps-20191217.html

I'll think of a way to avoid this in the future. I'd prefer to just maintain the package when new values are added, but it seems there is just no process on the side of the FIDO2 Alliance to notify developers about updates.

**Comment by ckruse** [comment]
Thanks for the fix.

**Comment by tanguilp** [comment]
You're welcome. The FIDO2 Alliance is working on a new, open metadata service that will replace this one. I'll implement it with better care of such errors as soon as it is made available.
